name: habitfit_mvp
description: MVP template for Habit + Fit + NutriSnap (Flutter + Firebase + Camera)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  flutter_riverpod: any
  firebase_core: any
  cloud_firestore: any
  firebase_messaging: any
  firebase_auth: any
  firebase_remote_config: any
  camera: any
  image_picker: any
  path_provider: any
  permission_handler: any
  tflite_flutter: any
  ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/models/
