// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6KW7F0773aHnI9L6wAcFEAj_5NmZs2Ks',
    appId: '1:83611695902:android:1eff6612f96c2837e9270f',
    messagingSenderId: '83611695902',
    projectId: 'flutterhabitfit',
    authDomain: 'flutterhabitfit.firebaseapp.com',
    storageBucket: 'flutterhabitfit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6KW7F0773aHnI9L6wAcFEAj_5NmZs2Ks',
    appId: '1:83611695902:android:1eff6612f96c2837e9270f',
    messagingSenderId: '83611695902',
    projectId: 'flutterhabitfit',
    storageBucket: 'flutterhabitfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNSM8andxwUzUdcByT7e9g8r2ELZb-0s',
    appId: '1:83611695902:ios:ca51185c8ffc330ee9270f',
    messagingSenderId: '83611695902',
    projectId: 'flutterhabitfit',
    storageBucket: 'flutterhabitfit.firebasestorage.app',
    iosClientId: '1:83611695902:ios:ca51185c8ffc330ee9270f',
    iosBundleId: 'com.leeyoungho.habitfitMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiNSM8andxwUzUdcByT7e9g8r2ELZb-0s',
    appId: '1:83611695902:ios:ca51185c8ffc330ee9270f',
    messagingSenderId: '83611695902',
    projectId: 'flutterhabitfit',
    storageBucket: 'flutterhabitfit.firebasestorage.app',
    iosClientId: '1:83611695902:ios:ca51185c8ffc330ee9270f',
    iosBundleId: 'com.leeyoungho.habitfitMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6KW7F0773aHnI9L6wAcFEAj_5NmZs2Ks',
    appId: '1:83611695902:android:1eff6612f96c2837e9270f',
    messagingSenderId: '83611695902',
    projectId: 'flutterhabitfit',
    storageBucket: 'flutterhabitfit.firebasestorage.app',
  );
}
